apiVersion: v1
kind: Secret
metadata:
  name: jsw-app-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_NAME: "${DB_NAME}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  PROJECT_LIMIT: "${PROJECT_LIMIT}"
  PROJECT_SIGNKEY: "${PROJECT_SIGNKEY}"
  PROJECT_DOMAIN: "${PUBLIC_DOMAIN}"
  PROJECT_HOST: "${PUBLIC_HOST}"
  VANNA_INTERNAL_TOKEN: "${VANNA_INTERNAL_TOKEN}"
  VANNA_DB_URL: "${VANNA_DB_URL}"
  VANNA_CHAT_MODEL: "${VANNA_CHAT_MODEL}"
  VANNA_EMBEDDING_MODEL: "${VANNA_EMBEDDING_MODEL}"
  VANNA_LLM_BASE_URL: "${VANNA_LLM_BASE_URL}"
  VANNA_LLM_API_KEY: "${VANNA_LLM_API_KEY}"
