apiVersion: v1
kind: Service
metadata:
  name: jsw-server-vanna
  namespace: app-local
  labels:
    app.kubernetes.io/name: java-sql-web
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: vanna-external
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: java-sql-web
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      nodePort: 32002
