from contextlib import contextmanager
from typing import Iterator

import psycopg

from .config import settings


@contextmanager
def get_conn() -> Iterator[psycopg.Connection]:
    """创建一个短生命周期 PostgreSQL 连接，供缓存和审计写入使用。"""

    with psycopg.connect(settings.vanna_db_url) as conn:
        yield conn


def init_db() -> None:
    """初始化 Vanna 运行所需的数据表和 pgvector 扩展。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            # pgvector 预留给上下文向量持久化使用；当前召回仍在内存中完成。
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
            # 缓存 JavaSqlWeb 返回的完整 schema 文本，避免上下文版本未变时重复整理。
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_context_cache (
                    cache_key varchar(256) PRIMARY KEY,
                    context_version varchar(256) NOT NULL,
                    dialect varchar(64) NOT NULL,
                    server_name varchar(128) NOT NULL,
                    db_name varchar(128) NOT NULL,
                    schema_text text NOT NULL,
                    matched_tables text[] NOT NULL DEFAULT '{}',
                    embedding_model_key varchar(512) NOT NULL DEFAULT '',
                    updated_at timestamp NOT NULL DEFAULT now()
                )
                """
            )
            cur.execute(
                "ALTER TABLE vanna_context_cache ADD COLUMN IF NOT EXISTS embedding_model_key varchar(512) NOT NULL DEFAULT ''"
            )
            # 保存表、字段、历史 SQL 等可检索片段；旧 embedding 字段保留给兼容升级。
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_context_embedding (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cache_key varchar(256) NOT NULL,
                    chunk_type varchar(32) NOT NULL,
                    chunk_key varchar(256) NOT NULL,
                    chunk_text text NOT NULL,
                    embedding vector(1536) NULL,
                    embedding_values real[] NULL,
                    embedding_dims integer NOT NULL DEFAULT 0,
                    updated_at timestamp NOT NULL DEFAULT now(),
                    CONSTRAINT uk_vanna_context_embedding UNIQUE (cache_key, chunk_type, chunk_key)
                )
                """
            )
            cur.execute("ALTER TABLE vanna_context_embedding ADD COLUMN IF NOT EXISTS embedding_values real[] NULL")
            cur.execute(
                "ALTER TABLE vanna_context_embedding ADD COLUMN IF NOT EXISTS embedding_dims integer NOT NULL DEFAULT 0"
            )
            # 记录每次生成结果、耗时和安全拦截状态，便于排查与审计。
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_audit_log (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    server_code varchar(64) NOT NULL,
                    db_name varchar(128) NOT NULL,
                    question text NOT NULL,
                    generated_sql text NULL,
                    matched_tables text[] NOT NULL DEFAULT '{}',
                    needs_clarification boolean NOT NULL DEFAULT false,
                    clarification_question text NULL,
                    warnings text[] NOT NULL DEFAULT '{}',
                    model_name varchar(128) NOT NULL,
                    response_status varchar(32) NOT NULL,
                    cost_millis integer NOT NULL DEFAULT 0,
                    created_at timestamp NOT NULL DEFAULT now()
                )
                """
            )
        conn.commit()
