from contextlib import contextmanager
from datetime import datetime, timedelta
from typing import Iterator

import psycopg

from .config import settings


@contextmanager
def get_conn() -> Iterator[psycopg.Connection]:
    """创建一个短生命周期 PostgreSQL 连接，供缓存、预热状态和审计写入使用。"""

    with psycopg.connect(settings.vanna_db_url) as conn:
        yield conn


def init_db() -> None:
    """初始化 Vanna 运行所需的数据表，并兼容补齐旧环境缺失字段。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_context_cache (
                    cache_key varchar(256) PRIMARY KEY,
                    context_version varchar(256) NOT NULL,
                    dialect varchar(64) NOT NULL,
                    server_name varchar(128) NOT NULL,
                    db_name varchar(128) NOT NULL,
                    schema_text text NOT NULL,
                    matched_tables text[] NOT NULL DEFAULT '{}',
                    embedding_model_key varchar(512) NOT NULL DEFAULT '',
                    updated_at timestamp NOT NULL DEFAULT now()
                )
                """
            )
            cur.execute(
                "ALTER TABLE vanna_context_cache ADD COLUMN IF NOT EXISTS embedding_model_key varchar(512) NOT NULL DEFAULT ''"
            )
            # 保存表、字段、历史 SQL 等可检索片段；旧 embedding 字段保留给兼容升级。
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_context_embedding (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cache_key varchar(256) NOT NULL,
                    chunk_type varchar(32) NOT NULL,
                    chunk_key varchar(256) NOT NULL,
                    chunk_text text NOT NULL,
                    embedding vector(1536) NULL,
                    embedding_values real[] NULL,
                    embedding_dims integer NOT NULL DEFAULT 0,
                    updated_at timestamp NOT NULL DEFAULT now(),
                    CONSTRAINT uk_vanna_context_embedding UNIQUE (cache_key, chunk_type, chunk_key)
                )
                """
            )
            cur.execute("ALTER TABLE vanna_context_embedding ADD COLUMN IF NOT EXISTS embedding_values real[] NULL")
            cur.execute(
                "ALTER TABLE vanna_context_embedding ADD COLUMN IF NOT EXISTS embedding_dims integer NOT NULL DEFAULT 0"
            )
            # 记录每次生成结果、耗时和安全拦截状态，便于排查与审计。
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_audit_log (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    server_code varchar(64) NOT NULL,
                    db_name varchar(128) NOT NULL,
                    question text NOT NULL,
                    generated_sql text NULL,
                    matched_tables text[] NOT NULL DEFAULT '{}',
                    needs_clarification boolean NOT NULL DEFAULT false,
                    clarification_question text NULL,
                    warnings text[] NOT NULL DEFAULT '{}',
                    model_name varchar(128) NOT NULL,
                    response_status varchar(32) NOT NULL,
                    cost_millis integer NOT NULL DEFAULT 0,
                    created_at timestamp NOT NULL DEFAULT now()
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_context_job_state (
                    cache_key varchar(256) PRIMARY KEY,
                    server_code varchar(64) NOT NULL,
                    db_name varchar(128) NOT NULL,
                    last_context_version varchar(256) NULL,
                    last_warmup_status varchar(32) NOT NULL DEFAULT 'PENDING',
                    last_warmup_started_at timestamp NULL,
                    last_warmup_finished_at timestamp NULL,
                    last_error_message text NULL,
                    next_retry_at timestamp NULL
                )
                """
            )
            cur.execute(
                "ALTER TABLE vanna_context_cache ADD COLUMN IF NOT EXISTS embedding_model_key varchar(512) NOT NULL DEFAULT ''"
            )
            cur.execute("ALTER TABLE vanna_context_embedding ADD COLUMN IF NOT EXISTS embedding_values real[] NULL")
            cur.execute(
                "ALTER TABLE vanna_context_embedding ADD COLUMN IF NOT EXISTS embedding_dims integer NOT NULL DEFAULT 0"
            )
        conn.commit()


def upsert_job_state(
    cache_key: str,
    server_code: str,
    db_name: str,
    context_version: str | None,
    status: str,
    error_message: str | None = None,
    next_retry_minutes: int | None = None,
) -> None:
    """记录某个库的预热状态，便于重启后继续调度与失败重试。"""

    next_retry_at = (
        datetime.now() + timedelta(minutes=next_retry_minutes)
        if next_retry_minutes and next_retry_minutes > 0
        else None
    )
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO vanna_context_job_state (
                    cache_key, server_code, db_name, last_context_version, last_warmup_status,
                    last_warmup_started_at, last_warmup_finished_at, last_error_message, next_retry_at
                )
                VALUES (%s, %s, %s, %s, %s, now(), CASE WHEN %s = 'SUCCESS' THEN now() ELSE NULL END, %s, %s)
                ON CONFLICT (cache_key) DO UPDATE SET
                    last_context_version = excluded.last_context_version,
                    last_warmup_status = excluded.last_warmup_status,
                    last_warmup_started_at = excluded.last_warmup_started_at,
                    last_warmup_finished_at = CASE
                        WHEN excluded.last_warmup_status = 'SUCCESS' THEN now()
                        ELSE vanna_context_job_state.last_warmup_finished_at
                    END,
                    last_error_message = excluded.last_error_message,
                    next_retry_at = excluded.next_retry_at
                """,
                (
                    cache_key,
                    server_code,
                    db_name,
                    context_version,
                    status,
                    status,
                    error_message,
                    next_retry_at,
                ),
            )
        conn.commit()


def load_cache_state(cache_key: str) -> tuple[str, str] | None:
    """读取当前 cache 的上下文版本与 embedding 模型标识。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT context_version, COALESCE(embedding_model_key, '') FROM vanna_context_cache WHERE cache_key = %s",
                (cache_key,),
            )
            row = cur.fetchone()
    if row is None:
        return None
    return str(row[0]), str(row[1] or "")


def persist_context_cache(
    cache_key: str,
    context_version: str,
    dialect: str,
    server_name: str,
    db_name: str,
    schema_text: str,
    matched_tables: list[str],
    embedding_model_key: str,
) -> None:
    """持久化完整 schema 文本与当前向量模型标识。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO vanna_context_cache (
                    cache_key, context_version, dialect, server_name, db_name,
                    schema_text, matched_tables, embedding_model_key, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, now())
                ON CONFLICT (cache_key) DO UPDATE SET
                    context_version = excluded.context_version,
                    dialect = excluded.dialect,
                    server_name = excluded.server_name,
                    db_name = excluded.db_name,
                    schema_text = excluded.schema_text,
                    matched_tables = excluded.matched_tables,
                    embedding_model_key = excluded.embedding_model_key,
                    updated_at = now()
                """,
                (
                    cache_key,
                    context_version,
                    dialect,
                    server_name,
                    db_name,
                    schema_text,
                    matched_tables,
                    embedding_model_key,
                ),
            )
        conn.commit()


def replace_chunk_embeddings(
    cache_key: str,
    chunks: list[tuple[str, str, str]],
    vectors: list[list[float]],
) -> None:
    """原子替换某个库的全部 chunk 向量缓存。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM vanna_context_embedding WHERE cache_key = %s", (cache_key,))
            for (chunk_type, chunk_key, chunk_text), vector in zip(chunks, vectors):
                cur.execute(
                    """
                    INSERT INTO vanna_context_embedding (
                        cache_key, chunk_type, chunk_key, chunk_text,
                        embedding_values, embedding_dims, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, now())
                    """,
                    (
                        cache_key,
                        chunk_type,
                        chunk_key,
                        chunk_text,
                        vector,
                        len(vector),
                    ),
                )
        conn.commit()


def has_complete_embeddings(cache_key: str, expected_count: int) -> bool:
    """检查当前 cache 下是否存在完整、可复用的 chunk 向量。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT
                    COUNT(*),
                    COALESCE(
                        SUM(
                            CASE
                                WHEN embedding_values IS NULL
                                    OR embedding_dims <= 0
                                    OR COALESCE(cardinality(embedding_values), 0) = 0
                                    OR COALESCE(cardinality(embedding_values), 0) <> embedding_dims
                                THEN 1
                                ELSE 0
                            END
                        ),
                        0
                    )
                FROM vanna_context_embedding
                WHERE cache_key = %s
                """,
                (cache_key,),
            )
            row = cur.fetchone()
    total = int((row or (0, 0))[0] or 0)
    invalid = int((row or (0, 0))[1] or 0)
    return total == expected_count and invalid == 0


def load_chunk_embeddings(cache_key: str) -> list[tuple[str, list[float], int]]:
    """读取某个库全部已持久化 chunk 文本和向量。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT chunk_text, embedding_values, embedding_dims
                FROM vanna_context_embedding
                WHERE cache_key = %s
                ORDER BY id ASC
                """,
                (cache_key,),
            )
            rows = cur.fetchall() or []
    result: list[tuple[str, list[float], int]] = []
    for chunk_text, embedding_values, embedding_dims in rows:
        vector = [float(value) for value in list(embedding_values or [])]
        result.append((str(chunk_text), vector, int(embedding_dims or 0)))
    return result
