from contextlib import contextmanager
from datetime import datetime, timedelta
from typing import Iterator

import psycopg

from .config import settings


@contextmanager
def get_conn() -> Iterator[psycopg.Connection]:
    """创建一个短生命周期 PostgreSQL 连接，供缓存和审计写入使用。"""

    with psycopg.connect(settings.vanna_db_url) as conn:
        yield conn


def init_db() -> None:
    """初始化 Vanna 运行所需的数据表和 pgvector 扩展。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            # pgvector 预留给上下文向量持久化使用；当前召回仍在内存中完成。
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
            # 缓存 JavaSqlWeb 返回的完整 schema 文本，避免上下文版本未变时重复整理。
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_context_cache (
                    cache_key varchar(256) PRIMARY KEY,
                    context_version varchar(256) NOT NULL,
                    dialect varchar(64) NOT NULL,
                    server_name varchar(128) NOT NULL,
                    db_name varchar(128) NOT NULL,
                    schema_text text NOT NULL,
                    matched_tables text[] NOT NULL DEFAULT '{}',
                    embedding_model_key varchar(512) NOT NULL DEFAULT '',
                    updated_at timestamp NOT NULL DEFAULT now()
                )
                """
            )
            cur.execute(
                "ALTER TABLE vanna_context_cache ADD COLUMN IF NOT EXISTS embedding_model_key varchar(512) NOT NULL DEFAULT ''"
            )
            # 保存表、字段、历史 SQL 等可检索片段；旧 embedding 字段保留给兼容升级。
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_context_embedding (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cache_key varchar(256) NOT NULL,
                    chunk_type varchar(32) NOT NULL,
                    chunk_key varchar(256) NOT NULL,
                    chunk_text text NOT NULL,
                    embedding vector(1536) NULL,
                    embedding_values real[] NULL,
                    embedding_dims integer NOT NULL DEFAULT 0,
                    updated_at timestamp NOT NULL DEFAULT now(),
                    CONSTRAINT uk_vanna_context_embedding UNIQUE (cache_key, chunk_type, chunk_key)
                )
                """
            )
            cur.execute("ALTER TABLE vanna_context_embedding ADD COLUMN IF NOT EXISTS embedding_values real[] NULL")
            cur.execute(
                "ALTER TABLE vanna_context_embedding ADD COLUMN IF NOT EXISTS embedding_dims integer NOT NULL DEFAULT 0"
            )
            # 记录每次生成结果、耗时和安全拦截状态，便于排查与审计。
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_audit_log (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    server_code varchar(64) NOT NULL,
                    db_name varchar(128) NOT NULL,
                    question text NOT NULL,
                    generated_sql text NULL,
                    matched_tables text[] NOT NULL DEFAULT '{}',
                    needs_clarification boolean NOT NULL DEFAULT false,
                    clarification_question text NULL,
                    warnings text[] NOT NULL DEFAULT '{}',
                    model_name varchar(128) NOT NULL,
                    response_status varchar(32) NOT NULL,
                    cost_millis integer NOT NULL DEFAULT 0,
                    created_at timestamp NOT NULL DEFAULT now()
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vanna_context_job_state (
                    cache_key varchar(256) PRIMARY KEY,
                    server_code varchar(64) NOT NULL,
                    db_name varchar(128) NOT NULL,
                    last_context_version varchar(256) NULL,
                    last_warmup_status varchar(32) NOT NULL DEFAULT 'PENDING',
                    last_warmup_started_at timestamp NULL,
                    last_warmup_finished_at timestamp NULL,
                    last_error_message text NULL,
                    next_retry_at timestamp NULL
                )
                """
            )
        conn.commit()


def upsert_job_state(
    cache_key: str,
    server_code: str,
    db_name: str,
    context_version: str | None,
    status: str,
    error_message: str | None = None,
    next_retry_minutes: int | None = None,
) -> None:
    """记录某个库的预热状态，便于重启后继续调度与失败重试。"""

    next_retry_at = (
        datetime.now() + timedelta(minutes=next_retry_minutes)
        if next_retry_minutes and next_retry_minutes > 0
        else None
    )
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO vanna_context_job_state (
                    cache_key, server_code, db_name, last_context_version, last_warmup_status,
                    last_warmup_started_at, last_warmup_finished_at, last_error_message, next_retry_at
                )
                VALUES (%s, %s, %s, %s, %s, now(), CASE WHEN %s = 'SUCCESS' THEN now() ELSE NULL END, %s, %s)
                ON CONFLICT (cache_key) DO UPDATE SET
                    last_context_version = excluded.last_context_version,
                    last_warmup_status = excluded.last_warmup_status,
                    last_warmup_started_at = excluded.last_warmup_started_at,
                    last_warmup_finished_at = CASE
                        WHEN excluded.last_warmup_status = 'SUCCESS' THEN now()
                        ELSE vanna_context_job_state.last_warmup_finished_at
                    END,
                    last_error_message = excluded.last_error_message,
                    next_retry_at = excluded.next_retry_at
                """,
                (
                    cache_key,
                    server_code,
                    db_name,
                    context_version,
                    status,
                    status,
                    error_message,
                    next_retry_at,
                ),
            )
        conn.commit()


def fetch_cached_embeddings(cache_key: str) -> list[tuple[str, list[float]]]:
    """读取某个库已经落盘的 chunk embedding。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT chunk_text, embedding::text
                FROM vanna_context_embedding
                WHERE cache_key = %s AND embedding IS NOT NULL
                ORDER BY id ASC
                """,
                (cache_key,),
            )
            rows = cur.fetchall()
    result: list[tuple[str, list[float]]] = []
    for chunk_text, embedding_text in rows:
        values = embedding_text.strip("[]")
        vector = [float(item) for item in values.split(",")] if values else []
        result.append((chunk_text, vector))
    return result


def save_chunk_embeddings(cache_key: str, chunks: list[tuple[str, str, str]], vectors: list[list[float]]) -> None:
    """把预计算好的 chunk embeddings 批量写入数据库。"""

    with get_conn() as conn:
        with conn.cursor() as cur:
            for (chunk_type, chunk_key, chunk_text), vector in zip(chunks, vectors):
                cur.execute(
                    """
                    INSERT INTO vanna_context_embedding (cache_key, chunk_type, chunk_key, chunk_text, embedding, updated_at)
                    VALUES (%s, %s, %s, %s, %s::vector, now())
                    ON CONFLICT (cache_key, chunk_type, chunk_key) DO UPDATE SET
                        chunk_text = excluded.chunk_text,
                        embedding = excluded.embedding,
                        updated_at = now()
                    """,
                    (
                        cache_key,
                        chunk_type,
                        chunk_key,
                        chunk_text,
                        "[" + ",".join(f"{value:.8f}" for value in vector) + "]",
                    ),
                )
        conn.commit()
