-- PostgreSQL 初始化脚本：由 postgres 官方镜像在空 PGDATA 上首次启动时执行。
-- 数据库由 POSTGRES_DB 创建，本脚本只初始化当前数据库内的应用表结构。

CREATE TABLE IF NOT EXISTS db_connect_config_tb (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  db_server_name varchar(45) NOT NULL,
  db_server_host varchar(45) NOT NULL,
  db_server_port varchar(45) NOT NULL,
  db_server_username varchar(45) NOT NULL,
  db_server_password varchar(45) NOT NULL,
  db_server_type varchar(45) NOT NULL,
  db_ssl_mode varchar(32) NOT NULL DEFAULT 'DEFAULT',
  create_time timestamp NOT NULL,
  db_group varchar(45) NOT NULL DEFAULT 'default'
);
COMMENT ON TABLE db_connect_config_tb IS '数据库连接配置表';
COMMENT ON COLUMN db_connect_config_tb.code IS '自增值';
COMMENT ON COLUMN db_connect_config_tb.db_server_name IS '服务器名';
COMMENT ON COLUMN db_connect_config_tb.db_server_host IS '服务器IP或域名';
COMMENT ON COLUMN db_connect_config_tb.db_server_port IS '服务器端口';
COMMENT ON COLUMN db_connect_config_tb.db_server_username IS '服务器用户名';
COMMENT ON COLUMN db_connect_config_tb.db_server_password IS '服务器密码';
COMMENT ON COLUMN db_connect_config_tb.db_server_type IS '服务器类型，如 mssql/mysql/mariadb/postgresql/clickhouse';
COMMENT ON COLUMN db_connect_config_tb.db_ssl_mode IS '连接安全模式';
COMMENT ON COLUMN db_connect_config_tb.create_time IS '创建时间';
COMMENT ON COLUMN db_connect_config_tb.db_group IS '数据库分组';

CREATE TABLE IF NOT EXISTS db_server_database_snapshot_tb (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_code integer NOT NULL,
  database_name varchar(128) NOT NULL,
  synced_at timestamp NOT NULL,
  CONSTRAINT uk_server_database UNIQUE (server_code, database_name)
);
CREATE INDEX IF NOT EXISTS idx_database_name ON db_server_database_snapshot_tb (database_name);
CREATE INDEX IF NOT EXISTS idx_synced_at ON db_server_database_snapshot_tb (synced_at);
COMMENT ON TABLE db_server_database_snapshot_tb IS '服务器库名快照表';
COMMENT ON COLUMN db_server_database_snapshot_tb.id IS '自增值';
COMMENT ON COLUMN db_server_database_snapshot_tb.server_code IS '实例编号';
COMMENT ON COLUMN db_server_database_snapshot_tb.database_name IS '库名';
COMMENT ON COLUMN db_server_database_snapshot_tb.synced_at IS '同步时间';

CREATE TABLE IF NOT EXISTS db_query_log (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query_ip varchar(45) NOT NULL,
  query_name varchar(45) NOT NULL,
  query_database varchar(45) NOT NULL,
  server_code integer NULL,
  db_session_id varchar(64) NULL,
  query_sqlscript varchar(8000) NOT NULL,
  query_consuming integer NULL,
  result_row_count integer NULL,
  query_time timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_server_session ON db_query_log (server_code, db_session_id);
COMMENT ON TABLE db_query_log IS '用户查询日志表';
COMMENT ON COLUMN db_query_log.code IS '自增值';
COMMENT ON COLUMN db_query_log.query_ip IS '查询人IP';
COMMENT ON COLUMN db_query_log.query_name IS '查询人';
COMMENT ON COLUMN db_query_log.query_database IS '查询语句的库';
COMMENT ON COLUMN db_query_log.server_code IS '查询目标实例';
COMMENT ON COLUMN db_query_log.db_session_id IS '目标库会话ID';
COMMENT ON COLUMN db_query_log.query_sqlscript IS '查询脚本';
COMMENT ON COLUMN db_query_log.query_consuming IS '查询耗时';
COMMENT ON COLUMN db_query_log.result_row_count IS '返回条数';
COMMENT ON COLUMN db_query_log.query_time IS '查询时间';

CREATE TABLE IF NOT EXISTS db_query_log_target_tb (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query_log_code integer NOT NULL,
  database_name varchar(100) NOT NULL,
  table_name varchar(200) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_query_log_code ON db_query_log_target_tb (query_log_code);
CREATE INDEX IF NOT EXISTS idx_database_table ON db_query_log_target_tb (database_name, table_name);
COMMENT ON TABLE db_query_log_target_tb IS '查询日志命中对象表';
COMMENT ON COLUMN db_query_log_target_tb.code IS '自增值';
COMMENT ON COLUMN db_query_log_target_tb.query_log_code IS '查询日志编号';
COMMENT ON COLUMN db_query_log_target_tb.database_name IS '数据库名';
COMMENT ON COLUMN db_query_log_target_tb.table_name IS '表名';

CREATE TABLE IF NOT EXISTS user_tb (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name varchar(45) NOT NULL,
  email varchar(100) NOT NULL,
  create_time timestamp NOT NULL,
  pass_word varchar(100) NOT NULL,
  token varchar(45) NOT NULL,
  auth_secret varchar(45) NULL,
  auth_status varchar(45) NOT NULL DEFAULT 'UNBIND',
  login_status varchar(45) NOT NULL DEFAULT 'LOGGING',
  account_status varchar(45) NOT NULL DEFAULT 'ACTIVE',
  oidc_sub varchar(256) NULL,
  access_token_hash varchar(64) NULL,
  access_token_expire_time timestamp NULL,
  CONSTRAINT uk_user_name UNIQUE (user_name),
  CONSTRAINT uk_email UNIQUE (email),
  CONSTRAINT uk_oidc_sub UNIQUE (oidc_sub)
);
COMMENT ON TABLE user_tb IS '用户表';
COMMENT ON COLUMN user_tb.code IS '自增值';
COMMENT ON COLUMN user_tb.user_name IS '用户名';
COMMENT ON COLUMN user_tb.email IS '用户邮箱';
COMMENT ON COLUMN user_tb.create_time IS '创建时间';
COMMENT ON COLUMN user_tb.pass_word IS '密码';
COMMENT ON COLUMN user_tb.token IS '登录临时令牌';
COMMENT ON COLUMN user_tb.auth_secret IS '二次验证密钥';
COMMENT ON COLUMN user_tb.auth_status IS '密保绑定状态';
COMMENT ON COLUMN user_tb.login_status IS '登录状态';
COMMENT ON COLUMN user_tb.account_status IS '账号状态';
COMMENT ON COLUMN user_tb.oidc_sub IS 'OIDC Subject 标识';
COMMENT ON COLUMN user_tb.access_token_hash IS '长期访问令牌哈希';
COMMENT ON COLUMN user_tb.access_token_expire_time IS '访问令牌过期时间';

CREATE TABLE IF NOT EXISTS user_security_task_tb (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_uuid_hash varchar(64) NOT NULL,
  user_code integer NOT NULL,
  task_type varchar(45) NOT NULL,
  task_status varchar(45) NOT NULL,
  expire_time timestamp NOT NULL,
  used_time timestamp NULL,
  created_by varchar(45) NOT NULL,
  created_time timestamp NOT NULL,
  CONSTRAINT uk_task_uuid_hash UNIQUE (task_uuid_hash)
);
CREATE INDEX IF NOT EXISTS idx_user_task_pending ON user_security_task_tb (user_code, task_status, created_time);
COMMENT ON TABLE user_security_task_tb IS '用户安全任务表';
COMMENT ON COLUMN user_security_task_tb.code IS '自增值';
COMMENT ON COLUMN user_security_task_tb.task_uuid_hash IS '任务UUID哈希';
COMMENT ON COLUMN user_security_task_tb.user_code IS '用户编号';
COMMENT ON COLUMN user_security_task_tb.task_type IS '任务类型';
COMMENT ON COLUMN user_security_task_tb.task_status IS '任务状态';
COMMENT ON COLUMN user_security_task_tb.expire_time IS '过期时间';
COMMENT ON COLUMN user_security_task_tb.used_time IS '使用时间';
COMMENT ON COLUMN user_security_task_tb.created_by IS '创建人';
COMMENT ON COLUMN user_security_task_tb.created_time IS '创建时间';

CREATE TABLE IF NOT EXISTS usergroup (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name varchar(45) NOT NULL,
  comment varchar(45) NULL
);
COMMENT ON TABLE usergroup IS '用户组表';
COMMENT ON COLUMN usergroup.code IS '编号';
COMMENT ON COLUMN usergroup.group_name IS '组名';
COMMENT ON COLUMN usergroup.comment IS '备注';

CREATE TABLE IF NOT EXISTS user_permissions (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_code integer NOT NULL,
  group_code integer NOT NULL
);
COMMENT ON TABLE user_permissions IS '用户与用户组关系表';
COMMENT ON COLUMN user_permissions.code IS '编号';
COMMENT ON COLUMN user_permissions.user_code IS '用户编号';
COMMENT ON COLUMN user_permissions.group_code IS '组编号';

CREATE TABLE IF NOT EXISTS db_permissions (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  db_code integer NOT NULL,
  group_code integer NOT NULL
);
COMMENT ON TABLE db_permissions IS '数据库权限表';
COMMENT ON COLUMN db_permissions.code IS '编号';
COMMENT ON COLUMN db_permissions.db_code IS '数据库编号';
COMMENT ON COLUMN db_permissions.group_code IS '组编号';

CREATE TABLE IF NOT EXISTS guid_sql_tb (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category varchar(20) NOT NULL,
  title varchar(100) NOT NULL,
  script varchar(8000) NOT NULL,
  server varchar(200) NOT NULL,
  database varchar(200) NOT NULL,
  create_date timestamp NOT NULL
);
COMMENT ON TABLE guid_sql_tb IS '常用 SQL 表';
COMMENT ON COLUMN guid_sql_tb.code IS '编号';
COMMENT ON COLUMN guid_sql_tb.category IS '分类';
COMMENT ON COLUMN guid_sql_tb.title IS '标题';
COMMENT ON COLUMN guid_sql_tb.script IS '语句';
COMMENT ON COLUMN guid_sql_tb.server IS '服务器';
COMMENT ON COLUMN guid_sql_tb.database IS '数据库';
COMMENT ON COLUMN guid_sql_tb.create_date IS '时间';

CREATE TABLE IF NOT EXISTS oidc_config_tb (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id varchar(256) NOT NULL,
  client_secret varchar(512) NOT NULL,
  openid_configuration_url varchar(512) NOT NULL,
  ssf_configuration_url varchar(512) NOT NULL,
  callback_url varchar(512) NOT NULL DEFAULT '',
  enabled boolean NOT NULL DEFAULT true,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL
);
COMMENT ON TABLE oidc_config_tb IS 'OIDC 配置表';
COMMENT ON COLUMN oidc_config_tb.code IS '自增主键';
COMMENT ON COLUMN oidc_config_tb.client_id IS 'OIDC Client ID';
COMMENT ON COLUMN oidc_config_tb.client_secret IS 'OIDC Client Secret';
COMMENT ON COLUMN oidc_config_tb.openid_configuration_url IS 'OpenID Discovery URL';
COMMENT ON COLUMN oidc_config_tb.ssf_configuration_url IS 'SSF Discovery URL';
COMMENT ON COLUMN oidc_config_tb.callback_url IS 'OIDC 回调地址（兼容保留，不再使用）';
COMMENT ON COLUMN oidc_config_tb.enabled IS '是否启用';
COMMENT ON COLUMN oidc_config_tb.created_time IS '创建时间';
COMMENT ON COLUMN oidc_config_tb.updated_time IS '更新时间';

CREATE TABLE IF NOT EXISTS passkey_auths_tb (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name varchar(100) NOT NULL,
  user_handle varchar(200) NOT NULL,
  credential_id varchar(200) NOT NULL,
  public_key varchar(200) NOT NULL,
  user_agent varchar(200) NOT NULL,
  create_date timestamp NOT NULL
);
COMMENT ON TABLE passkey_auths_tb IS 'WebAuthn 凭据表';
COMMENT ON COLUMN passkey_auths_tb.code IS '编号';
COMMENT ON COLUMN passkey_auths_tb.user_name IS '用户名';
COMMENT ON COLUMN passkey_auths_tb.user_handle IS '用户标识';
COMMENT ON COLUMN passkey_auths_tb.credential_id IS 'credential_id';
COMMENT ON COLUMN passkey_auths_tb.public_key IS 'public_key';
COMMENT ON COLUMN passkey_auths_tb.user_agent IS 'user agent';
COMMENT ON COLUMN passkey_auths_tb.create_date IS '时间';

CREATE TABLE IF NOT EXISTS webauthn_request_tb (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_type varchar(32) NOT NULL,
  request_key varchar(128) NOT NULL,
  request_json text NOT NULL,
  expire_time timestamp NOT NULL,
  created_time timestamp NOT NULL,
  CONSTRAINT uk_type_key UNIQUE (request_type, request_key)
);
CREATE INDEX IF NOT EXISTS idx_expire_time ON webauthn_request_tb (expire_time);
COMMENT ON TABLE webauthn_request_tb IS 'WebAuthn 一次性请求存储表';
COMMENT ON COLUMN webauthn_request_tb.code IS '自增值';
COMMENT ON COLUMN webauthn_request_tb.request_type IS '请求类型';
COMMENT ON COLUMN webauthn_request_tb.request_key IS '请求关联键';
COMMENT ON COLUMN webauthn_request_tb.request_json IS '序列化后的请求';
COMMENT ON COLUMN webauthn_request_tb.expire_time IS '过期时间';
COMMENT ON COLUMN webauthn_request_tb.created_time IS '创建时间';

CREATE TABLE IF NOT EXISTS oidc_login_state_tb (
  code integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usage_type varchar(32) NOT NULL,
  state_key varchar(128) NOT NULL,
  code_verifier varchar(255) NOT NULL,
  expire_time timestamp NOT NULL,
  created_time timestamp NOT NULL,
  CONSTRAINT uk_usage_state UNIQUE (usage_type, state_key)
);
CREATE INDEX IF NOT EXISTS idx_oidc_login_state_expire_time ON oidc_login_state_tb (expire_time);
COMMENT ON TABLE oidc_login_state_tb IS 'OIDC 登录/授权的一次性 PKCE state 存储表';
COMMENT ON COLUMN oidc_login_state_tb.code IS '自增值';
COMMENT ON COLUMN oidc_login_state_tb.usage_type IS 'State 用途：admin 表示管理端授权，login 表示登录页授权';
COMMENT ON COLUMN oidc_login_state_tb.state_key IS 'OIDC 授权请求中的 state 参数';
COMMENT ON COLUMN oidc_login_state_tb.code_verifier IS '与 state 绑定的 PKCE code_verifier';
COMMENT ON COLUMN oidc_login_state_tb.expire_time IS '过期时间';
COMMENT ON COLUMN oidc_login_state_tb.created_time IS '创建时间';

-- 兼容历史 MySQL/MariaDB 元库结构补丁。
-- 这部分可以在迁移后的 PostgreSQL 数据库中单独重复执行，用于补齐旧结构缺失字段。

ALTER TABLE db_connect_config_tb
  ADD COLUMN IF NOT EXISTS db_ssl_mode varchar(32) NOT NULL DEFAULT 'DEFAULT',
  ADD COLUMN IF NOT EXISTS db_group varchar(45) NOT NULL DEFAULT 'default';
COMMENT ON COLUMN db_connect_config_tb.db_ssl_mode IS '连接安全模式';
COMMENT ON COLUMN db_connect_config_tb.db_group IS '数据库分组';

ALTER TABLE db_query_log
  ADD COLUMN IF NOT EXISTS query_database varchar(45) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS server_code integer NULL,
  ADD COLUMN IF NOT EXISTS db_session_id varchar(64) NULL,
  ADD COLUMN IF NOT EXISTS query_consuming integer NULL,
  ADD COLUMN IF NOT EXISTS result_row_count integer NULL;
CREATE INDEX IF NOT EXISTS idx_server_session ON db_query_log (server_code, db_session_id);
COMMENT ON COLUMN db_query_log.query_database IS '查询语句的库';
COMMENT ON COLUMN db_query_log.server_code IS '查询目标实例';
COMMENT ON COLUMN db_query_log.db_session_id IS '目标库会话ID';
COMMENT ON COLUMN db_query_log.query_consuming IS '查询耗时';
COMMENT ON COLUMN db_query_log.result_row_count IS '返回条数';

ALTER TABLE user_tb
  ALTER COLUMN pass_word TYPE varchar(100),
  ADD COLUMN IF NOT EXISTS auth_secret varchar(45) NULL,
  ADD COLUMN IF NOT EXISTS auth_status varchar(45) NOT NULL DEFAULT 'UNBIND',
  ADD COLUMN IF NOT EXISTS login_status varchar(45) NOT NULL DEFAULT 'LOGGING',
  ADD COLUMN IF NOT EXISTS account_status varchar(45) NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS oidc_sub varchar(256) NULL,
  ADD COLUMN IF NOT EXISTS access_token_hash varchar(64) NULL,
  ADD COLUMN IF NOT EXISTS access_token_expire_time timestamp NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_oidc_sub ON user_tb (oidc_sub);
COMMENT ON COLUMN user_tb.auth_secret IS '二次验证密钥';
COMMENT ON COLUMN user_tb.auth_status IS '密保绑定状态';
COMMENT ON COLUMN user_tb.login_status IS '登录状态';
COMMENT ON COLUMN user_tb.account_status IS '账号状态';
COMMENT ON COLUMN user_tb.oidc_sub IS 'OIDC Subject 标识';
COMMENT ON COLUMN user_tb.access_token_hash IS '长期访问令牌哈希';
COMMENT ON COLUMN user_tb.access_token_expire_time IS '访问令牌过期时间';

ALTER TABLE oidc_config_tb
  ADD COLUMN IF NOT EXISTS ssf_configuration_url varchar(512) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS callback_url varchar(512) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN oidc_config_tb.ssf_configuration_url IS 'SSF Discovery URL';
COMMENT ON COLUMN oidc_config_tb.callback_url IS 'OIDC 回调地址（兼容保留，不再使用）';
COMMENT ON COLUMN oidc_config_tb.enabled IS '是否启用';
COMMENT ON COLUMN oidc_config_tb.created_time IS '创建时间';
COMMENT ON COLUMN oidc_config_tb.updated_time IS '更新时间';

ALTER TABLE webauthn_request_tb
  ADD COLUMN IF NOT EXISTS request_key varchar(128) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS request_json text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS created_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE UNIQUE INDEX IF NOT EXISTS uk_type_key ON webauthn_request_tb (request_type, request_key);
CREATE INDEX IF NOT EXISTS idx_expire_time ON webauthn_request_tb (expire_time);
COMMENT ON COLUMN webauthn_request_tb.request_key IS '请求关联键';
COMMENT ON COLUMN webauthn_request_tb.request_json IS '序列化后的请求';
COMMENT ON COLUMN webauthn_request_tb.created_time IS '创建时间';

ALTER TABLE oidc_login_state_tb
  ADD COLUMN IF NOT EXISTS state_key varchar(128) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS created_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE UNIQUE INDEX IF NOT EXISTS uk_usage_state ON oidc_login_state_tb (usage_type, state_key);
CREATE INDEX IF NOT EXISTS idx_oidc_login_state_expire_time ON oidc_login_state_tb (expire_time);
COMMENT ON COLUMN oidc_login_state_tb.state_key IS 'OIDC 授权请求中的 state 参数';
COMMENT ON COLUMN oidc_login_state_tb.created_time IS '创建时间';
