-- 为已存在的 PG 实例补齐 Vanna 独立数据库、角色与向量扩展。
--
-- 注意：
-- 1. PostgreSQL 不允许在 DO / function / transaction 里执行 CREATE DATABASE。
-- 2. 因此本脚本假定：
--    - 角色 jsw_vanna 已存在，或由外部命令先创建
--    - 数据库 jsw_vanna_db 已存在，或由外部命令先创建
-- 3. 推荐执行顺序：
--    - 先在 postgres 库里创建角色和数据库
--    - 再用本脚本连接 jsw_vanna_db 创建扩展和表

\connect jsw_vanna_db

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS vanna_context_cache (
  cache_key varchar(256) PRIMARY KEY,
  context_version varchar(256) NOT NULL,
  dialect varchar(64) NOT NULL,
  server_name varchar(128) NOT NULL,
  db_name varchar(128) NOT NULL,
  schema_text text NOT NULL,
  matched_tables text[] NOT NULL DEFAULT '{}',
  embedding_model_key varchar(512) NOT NULL DEFAULT '',
  updated_at timestamp NOT NULL DEFAULT now()
);
COMMENT ON TABLE vanna_context_cache IS 'Vanna 问数上下文缓存表';
COMMENT ON COLUMN vanna_context_cache.cache_key IS 'server/db 维度缓存键';
COMMENT ON COLUMN vanna_context_cache.context_version IS '上下文版本号';
COMMENT ON COLUMN vanna_context_cache.dialect IS 'SQL 方言';
COMMENT ON COLUMN vanna_context_cache.server_name IS '服务器名称';
COMMENT ON COLUMN vanna_context_cache.db_name IS '数据库名称';
COMMENT ON COLUMN vanna_context_cache.schema_text IS '拼装后的 schema 文本';
COMMENT ON COLUMN vanna_context_cache.matched_tables IS '上下文中的表名数组';
COMMENT ON COLUMN vanna_context_cache.embedding_model_key IS '当前持久化 chunk 向量对应的 embedding 模型标识';
COMMENT ON COLUMN vanna_context_cache.updated_at IS '更新时间';

CREATE TABLE IF NOT EXISTS vanna_context_embedding (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cache_key varchar(256) NOT NULL,
  chunk_type varchar(32) NOT NULL,
  chunk_key varchar(256) NOT NULL,
  chunk_text text NOT NULL,
  embedding vector(1536) NULL,
  embedding_values real[] NULL,
  embedding_dims integer NOT NULL DEFAULT 0,
  updated_at timestamp NOT NULL DEFAULT now(),
  CONSTRAINT uk_vanna_context_embedding UNIQUE (cache_key, chunk_type, chunk_key)
);
CREATE INDEX IF NOT EXISTS idx_vanna_context_embedding_cache_key ON vanna_context_embedding (cache_key);
COMMENT ON TABLE vanna_context_embedding IS 'Vanna 上下文分块及向量表';
COMMENT ON COLUMN vanna_context_embedding.id IS '自增主键';
COMMENT ON COLUMN vanna_context_embedding.cache_key IS 'server/db 维度缓存键';
COMMENT ON COLUMN vanna_context_embedding.chunk_type IS '分块类型';
COMMENT ON COLUMN vanna_context_embedding.chunk_key IS '分块唯一键';
COMMENT ON COLUMN vanna_context_embedding.chunk_text IS '分块文本';
COMMENT ON COLUMN vanna_context_embedding.embedding IS '向量';
COMMENT ON COLUMN vanna_context_embedding.embedding_values IS '当前实际使用的持久化向量数组';
COMMENT ON COLUMN vanna_context_embedding.embedding_dims IS 'embedding_values 的维度';
COMMENT ON COLUMN vanna_context_embedding.updated_at IS '更新时间';

CREATE TABLE IF NOT EXISTS vanna_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_code varchar(64) NOT NULL,
  db_name varchar(128) NOT NULL,
  question text NOT NULL,
  generated_sql text NULL,
  matched_tables text[] NOT NULL DEFAULT '{}',
  needs_clarification boolean NOT NULL DEFAULT false,
  clarification_question text NULL,
  warnings text[] NOT NULL DEFAULT '{}',
  model_name varchar(128) NOT NULL,
  response_status varchar(32) NOT NULL,
  cost_millis integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_vanna_audit_log_created_at ON vanna_audit_log (created_at DESC);
COMMENT ON TABLE vanna_audit_log IS 'Vanna 问数审计日志表';
COMMENT ON COLUMN vanna_audit_log.id IS '自增主键';
COMMENT ON COLUMN vanna_audit_log.server_code IS '目标服务器编号';
COMMENT ON COLUMN vanna_audit_log.db_name IS '目标数据库名';
COMMENT ON COLUMN vanna_audit_log.question IS '用户自然语言问题';
COMMENT ON COLUMN vanna_audit_log.generated_sql IS '生成的 SQL';
COMMENT ON COLUMN vanna_audit_log.matched_tables IS '命中的表名';
COMMENT ON COLUMN vanna_audit_log.needs_clarification IS '是否需要澄清';
COMMENT ON COLUMN vanna_audit_log.clarification_question IS '澄清问题';
COMMENT ON COLUMN vanna_audit_log.warnings IS '警告信息';
COMMENT ON COLUMN vanna_audit_log.model_name IS '使用的模型名';
COMMENT ON COLUMN vanna_audit_log.response_status IS '生成状态';
COMMENT ON COLUMN vanna_audit_log.cost_millis IS '耗时毫秒';
COMMENT ON COLUMN vanna_audit_log.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS vanna_context_job_state (
  cache_key varchar(256) PRIMARY KEY,
  server_code varchar(64) NOT NULL,
  db_name varchar(128) NOT NULL,
  last_context_version varchar(256) NULL,
  last_warmup_status varchar(32) NOT NULL DEFAULT 'PENDING',
  last_warmup_started_at timestamp NULL,
  last_warmup_finished_at timestamp NULL,
  last_error_message text NULL,
  next_retry_at timestamp NULL
);
COMMENT ON TABLE vanna_context_job_state IS 'Vanna 预热任务状态表';
COMMENT ON COLUMN vanna_context_job_state.cache_key IS 'server/db 维度缓存键';
COMMENT ON COLUMN vanna_context_job_state.server_code IS '目标服务器编号';
COMMENT ON COLUMN vanna_context_job_state.db_name IS '目标数据库名';
COMMENT ON COLUMN vanna_context_job_state.last_context_version IS '最近一次预热成功的上下文版本';
COMMENT ON COLUMN vanna_context_job_state.last_warmup_status IS '最近一次预热状态';
COMMENT ON COLUMN vanna_context_job_state.last_warmup_started_at IS '最近一次预热开始时间';
COMMENT ON COLUMN vanna_context_job_state.last_warmup_finished_at IS '最近一次预热完成时间';
COMMENT ON COLUMN vanna_context_job_state.last_error_message IS '最近一次失败原因';
COMMENT ON COLUMN vanna_context_job_state.next_retry_at IS '下次允许重试时间';

ALTER DATABASE jsw_vanna_db OWNER TO jsw_vanna;
GRANT ALL PRIVILEGES ON DATABASE jsw_vanna_db TO jsw_vanna;
GRANT USAGE, CREATE ON SCHEMA public TO jsw_vanna;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jsw_vanna;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jsw_vanna;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO jsw_vanna;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO jsw_vanna;
