apiVersion: v1
kind: Service
metadata:
  name: jsw-db-pg-np
  namespace: app-local
spec:
  type: NodePort
  selector:
    app: jsw-db-pg
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30002
