#%RAML 1.0
title: javaSqlWeb
version: v1
baseUri: http://127.0.0.1:8002

/health:
  get:
/database:
  /serverlist:
    get:
      body:
        application/json:
      responses:
        200:
  /dblist/{serverCode}:
    get:
    uriParameters:
      serverCode:
        type: string
        example: "1"
  /tablelist/{serverCode}/{dbname}:
    get:
      body:
        application/json:
    uriParameters:
      serverCode:
        type: string
        example: "1"
      dbname:
        type: string
        example: master
  /columnslist/{serverCode}/{dbName}/{tableName}:
    uriParameters:
      serverCode:
        type: string
        example: "1"
      dbName:
        type: string
        example: master
      tableName:
        type: string
        example: MSreplication_options
    get:
      body:
        application/json:
      responses:
        200:
  /indexeslist/{serverCode}/{dbName}/{tableName}:
    uriParameters:
      serverCode:
        type: string
        example: "1"
      dbName:
        type: string
        example: master
      tableName:
        type: string
        example: MSreplication_options
    get:
      body:
        application/json:
      responses:
        200:
  /query/{serverCode}/{dbName}:
    post:
      headers:
        User-Token:
          type: string
      body:
        text/plain:
          example: |
            select * from user_score_log
      responses:
        200:
    uriParameters:
      serverCode:
        type: string
        example: "1"
      dbName:
        type: string
        example: master
  /storedprocedures/{serverCode}/{dbName}:
    get:
      responses:
        200:
    uriParameters:
      serverCode:
        type: string
        example: "1"
      dbName:
        type: string
        example: master
  /storedprocedures/{serverCode}/{dbName}/{spName}:
    get:
      responses:
        200:
    uriParameters:
      serverCode:
        type: string
        example: "1"
      dbName:
        type: string
        example: master
      spName:
        type: string
        example: master
/user:
  /check:
    get:
      headers:
        User-Token:
          type: string
      responses:
        200:
  /login:
    post:
      body:
        application/json:
          example: |
            {
              "userName": "admin",
              "passWord": "admin"
            }
  /bindotp:
    post:
      body:
        application/json:
          example: |
            {
              "token": "aaaaaaa",
              "otpPass": "123456"
            }
  /verifyotp:
    post:
      body:
        application/json:
          example: |
            {
              "token": "aaaaaaa",
              "otpPass": "123456"
            }
  /create_user/{user_name}:
    get:

      headers:
        sign:
          type: string
      responses:
        200:
      queryParameters:
        timestamp:
          type: string
    uriParameters:
      user_name:
        type: string
/api:
  /backstage:
    /querylog:
      get:
        responses:
          200:
    /connlist:
      get:
        responses:
          200:
    /userlist:
      get:
    /adduser:
      post:
        body:
          application/json:
            example: |
              {}
    /deluser:
      post:
        body:
          application/json:
            example: |
              {}
    /addserver:
      post:
        body:
          application/json:
            example: |
              {}
    /testserver:
      post:
        body:
          application/json:
            example: |
              {}
    /delserver:
      post:
        body:
          application/json:
            example: |
              {}
    /usergroups:
      get:
        headers:
          User-Token:
            type: string
    /add_usergroups:
      post:
        headers:
          User-Token:
            type: string
            example: "3bfb64a7-7020-43f1-ab3a-51b4d97f1398"
        body:
          application/json:
            example: |
              {"userGroup": {"groupName": "b", "comment": "t"},
               "userList": [{"code":1},{"code":2}]}
    /db_perm:
      get:
        headers:
          User-Token:
            type: string
