#%RAML 1.0
title: javaSqlAdmin
version: v1
baseUri: http://127.0.0.1:8002

/database:
  /infoall:
    get:
      body:
        application/json:
      responses:
        200:
  /dblist/{dbcode}:
    get:
    uriParameters:
      dbcode:
        type: string
        example: 1
  /tablelist/{dbcode}/{dbname}:
    get:
      uriParameters:
        dbcode:
          type: string
          example: 1
        dbname:
          type: string
          example: 1
