package org.guohai.javasqlweb.beans.webauth;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NonNull;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum AttestationConveyancePreference {

    /**
     * Indicates that the Relying Party is not interested in authenticator attestation.
     *
     * <p>For example, in order to potentially avoid having to obtain user consent to relay
     * identifying information to the Relying Party, or to save a roundtrip to an <a
     * href="https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#attestation-ca">Attestation CA</a>.
     *
     * <p>This is the default value.
     */
    NONE("none"),
    INDIRECT("indirect"),

    /**
     * Indicates that the Relying Party wants to receive the attestation statement as generated by the
     * authenticator.
     */
    DIRECT("direct"),
    ENTERPRISE("enterprise");
    @Getter
    @NonNull
    private final String value;
}
